### ISSUE TITLE
New Article "How a Munich-based Game Studio is Using WordPress and Gutenberg to Power Its Website"

### ISSUE THREAD

**Issue by Luehrsen** [dseidl/awesome-gutenberg#3]
https://wptavern.com/how-a-munich-based-game-studio-is-using-wordpress-and-gutenberg-to-power-its-website

**Comment by dseidl** [comment]
hmm, nice article! on the one hand the repo should be developer focussed. but i can think of a new "Case Studies" section. i'll think about it. If you want you can create a pull request with the new section.

**Comment by dseidl** [comment]
i've added the link, thanks!
